# Generated by Django 5.2.8 on 2025-11-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api1', '0001_initial'),
        ('api7', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], max_length=20)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('reseña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api7.reseña')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.usuario')),
            ],
        ),
    ]
